sudo: false
language: node_js
node_js:
- stable
before_script:
- npm install -g mocha
deploy:
  provider: heroku
  buildpack: node_js
  api_key:
    secure: lFCu0b3v6DDpeWJkAMTHXwU+CY+zC4G4EkfOCNaO9i3Bl1AKfq+QIa0tnPwiY+ECmAB27q/00YaAck4r0QiioJEYqVE06f4uooMn3LclL3X6EPxXDWiwt+jn8cO48bTWi0wYfC/8h+yPYtHkQRZC/xb9rtPPpk1Sfe+C7DneUzleM3c9nfcIZegxXFI/SKoejr8rn6+FbRZQuK2iG8wZoX/fLZ+OjyYz6+UunV6w4kreX0XggFUGUVrikCguYU1d4zSemn93NEN0wtMg8avSlUsICdu7ZztZFO31uQA3R/B4/8tC0fbWEmQAHtV+JSo9S4r2vko236glvCEzFVbjaQeCUS9Yi6g78FN9zKwhySylE5Dge2WBrZNsZoNW8VOw1pK6av1usHtNoa4ZhpmNVpBavafhjx3JtvbCY4dXgy0Ks3Zo5WlGel/jwWzz9wq4eRXx0kYlzA/6q4AQ/gxWTQf3BlLUG6wb11yjDEbwyoGDrtB5oCuoq1HWkivygvayFnNn8HHQMORCOvn1CYCDX49Qn9h9tISSXHjszyz/I+jfrnNJr5RxGkrtoqvntpc9uyB73lWuDzScLXRxRQ59FpIGLML4u4U2+AqiY/zUuXj+ROrrq7uy2bk3jA3oedOmUQpYyO703yCPK+z9vwu2z93uRVufsVKlna/cF7qLjXQ=
  app: eduraam-router-staging
  on:
    branch: master
    repo: PerceptumNL/lean-eduraam-router
